apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
      streamingEnabled:
        search: true
